# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Dense Future
tagline:          'Improving human outcomes'
description:      'Making humanity more efficient through density'
url:              http://densefuture.com
baseurl:          /

author:
  name:           'Ben Schiendelman'
  url:            https://twitter.com/benschie

paginate:         5
