# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Dense Future
tagline:          'Improving human outcomes'
description:      ''
url:              http://densefuture.com
baseurl:          http://densefuture.com/

author:
  name:           'Ben Schiendelman'
  url:            https://twitter.com/benschie

paginate:         5
